### ISSUE TITLE
fix menu functionality on homepage

### ISSUE THREAD

**Issue by nicwinn** [uthsc/UTHSC#21]

**Comment by nicwinn** [comment]
there must have been a different bug that was squished. This no longer seems to be an issue.

**Comment by nicwinn** [comment]
I neglected to actually try this on my iPhone. Not sure why it works properly in the Chrome iOS emulator.

**Comment by ctbarber** [comment]
The UTHSC menu at the bottom doesn't work. Two things, can you see if this works on Android. THen we need to figure out why it doesn't work on iPhone

**Comment by gpspake** [comment]
Please include descriptions... it's difficult to tell what the problem is here.
![issue](https://cloud.githubusercontent.com/assets/3385690/7751009/221660a2-ff9d-11e4-819d-0ac7d6a1a536.JPG)
If this is about when the menu shows up, the user agent check currently just checks for iphone/ipad so it's going to show in chrome and ff on ios devices as well as safari.
That will need to be updated to target safari specifically. 

Is that what this issue is about?

**Comment by gpspake** [comment]
Description: Homepage off canvas menu does not work on iOS.
To reproduce, tap the menu button at the bottom of the screen on an iOS device. menu seems to be working properly on android and on desktop.

**Comment by gpspake** [comment]
I think @nicwinn said this is just a matter of copying some html over from the template.

**Comment by nicwinn** [comment]
removed foundation class .right
button.nav-toggler.toggle-push-right**.right**
![image](https://cloud.githubusercontent.com/assets/9751044/7756413/b1cd235c-ffc0-11e4-88d5-efb7bb8b641e.png)
